### PR TITLE
restructure guide 

### PR DESCRIPTION
**Pull request by bradfordcondon**
screen shot 2018-11-15 at 9 43 10 am

I'm just confused at the document levels, honestly.  @MingChen0919 does "* Uploaded XML: starts with an uploaded XML." exist as a guide?  If so where?

The big long guide, we need to break up into sections better.  IE define 3 or 4 main sections.  I probably need to actually follow the guide to do that...

"* Aurora Galaxy Tool: this option starts with an template file for developing an Aurora Galaxy Tool." is just a link to aurora which is totally fine.

### CODE REVIEW

**Comment by MingChen0919** [comment]
The guide for `Uploaded XML: starts with an uploaded XML.`  does not exist yet.

**Comment by MingChen0919** [comment]
What do you think if the menu tree is like this:

* Launching GTG
* Build Tool XML
    + Start from Scratch
    + Start with an Uploaded XML
    + Build Aurora Galaxy Tools

**Comment by bradfordcondon** [comment]
yep, thanks!  now that im trying out the tool it makes sense to me.

screen shot 2018-11-15 at 10 00 25 am

**Comment by bradfordcondon** [comment]
im going to merge so its easier to work on subissues (guide is split)

**Comment by MingChen0919** [comment]
I was about to say `reorder the three options` like this #10 . But i can change this later.

**Pull request merged**
