### PR TITLE
Re header scratch guide

### PR DESCRIPTION
**Pull request by bradfordcondon**
@MingChen0919 i made a lot of changes, it would be great if you could verify its still accurate.  I probably need to make another run through it to standardize my changes but i didnt realize what was going on until a few steps in...

### CODE REVIEW

**Comment by MingChen0919** [comment]
ok, i am pulling the update to verify.

**Comment by MingChen0919** [comment]
Looks good to me. I had to run `make html` to build the html to see your updates. Do you need to run that before you merge? Or is it automatically built by sphinx?

**Comment by bradfordcondon** [comment]
its automatically built by RTD.  if it looks good we can merge as is.

**Comment by MingChen0919** [comment]
I see. yeah. You can merge it.

**Pull request merged**
